### ISSUE TITLE
[bug]修复没有打过牌时收牌引起的bug

### ISSUE THREAD

**Issue by M-Riku** [M-Riku/RedFive#7]
```
TypeError: Cannot read property 'playedPokers' of undefined
    at exports.regretCards (/usr/src/app/controllers/gameAdmin.js:59:17)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
```

**Comment by M-Riku** [comment]
dd863fe1524b0ea58f6d0e57000a669d8376fefe
